groups:
  - name: ci
    jobs:
      - pr
  - name: meta
    jobs:
      - update-pipeline

resource_types:
  - name: cron-resource
    type: docker-image
    source:
      repository: cftoolsmiths/cron-resource
      tag: latest
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource
      username: ((docker_hub_username))
      password: ((docker_hub_authtoken))

resources:
  - name: related-links-pr
    type: pull-request
    source:
      access_token: ((concourse_ci_access_token))
      repository: alphagov/govuk-related-links-recommender
      disable_forks: true
    check_every: 1m
  - name: related-links-recommender-repo
    type: git
    source:
      uri: https://github.com/alphagov/govuk-related-links-recommender.git

jobs:
  - name: update-pipeline
    plan:
      - get: related-links-recommender-repo
        trigger: true
      - set_pipeline: govuk-related-links
        file: related-links-recommender-repo/concourse.yml
  - name: pr
    plan:
      - get: related-links-pr
        trigger: true
        version: every
      - put: related-links-pr
        params:
          path: related-links-pr
          status: pending
      - task: run-python-tests-and-linting
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 3.6
              username: ((docker_hub_username))
              password: ((docker_hub_authtoken))
          inputs:
            - name: related-links-pr
          run:
            path: bash
            args:
              - -c
              - |
                set -e pipefail

                pip install -r requirements.txt
                flake8 src
                pytest tests/unit
            dir: related-links-pr
      - task: run-ruby-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: 2.6
              username: ((docker_hub_username))
              password: ((docker_hub_authtoken))
          inputs:
            - name: related-links-pr
          run:
            path: bash
            args:
              - -c
              - |
                set -e pipefail

                gem install bundler
                bundle
                rspec spec
            dir: related-links-pr
      - put: related-links-pr
        params:
          path: related-links-pr
          status: success
    on_failure:
      put: related-links-pr
      params:
        path: related-links-pr
        status: failure
